#!/usr/bin/env python

import sys
from subprocess import check_output

# on definit un type de modification
typeModification = ['FEATURE', 'BUG']

# recuperer l'argument 1 (ici le chemin du fichier contenant le message du commit)
commitMsgFilepath = sys.argv[1]

#recuperer la branche
branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
print "commit sur la branche '%s'" % branch

# on lit le message du commit dans le fichier
with open(commitMsgFilepath, 'r') as f:
  content = f.read()
  # on verifie que le message du commit commence bien par un type de modification
  if not content.startswith(typeModification[0]) and not content.startswith(typeModification[1]):
    print "Erreur de commit, le message doit commencer par le type de modification : FEATURE ou BUG"
    sys.exit(1)